#This script will send the png files within the charts directory that were generated by the createCharts.py file
import smtplib, glob, os, ssl, getpass

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage

subject = "Technical Analysis Charts"
body = "These are the charts produced by our TA bot! Have a look at the most active stocks' TA charts!"
#You should want to use whatever emails you desire to test (you'll need to loosen the security on a gmail to use SSL)
sender_email = "exampleemail1@gmail.com" 
receiver_email = "exampleemail2@gmail.com"
password = ""

message = MIMEMultipart()
message["From"] = sender_email
message["To"] = receiver_email
message["Subject"] = subject

message.attach(MIMEText(body, "plain")) 

path = "charts/" #This is the directory that will hold pngs
pngfiles = glob.glob( os.path.join(path, "*.png"))
for file in pngfiles:
    fp = open(file, 'rb') #read file in binary mode
    img = MIMEImage(fp.read()) #make image
    img.add_header(
        "Content-Disposition",
        f"attachment; filename= {file}",
    ) 
    fp.close() #close when finished
    message.attach(img) #attach image to message

context = ssl.create_default_context()

def main():
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, message.as_string())
        print('Sent an email!')


if __name__=='__main__':
    main()